name: Development

on: [push, pull_request]

jobs:
  test:
    name: ${{matrix.ruby}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}-latest
    continue-on-error: ${{matrix.experimental}}
    
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
        
        ruby:
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
        
        experimental: [false]
        env: [""]
        
        include:
          - os: ubuntu
            ruby: truffleruby
            experimental: true
            env: JRUBY_OPTS="--debug -X+O"
          - os: ubuntu
            ruby: jruby
            experimental: true
            env: 'JRUBY_OPTS="-X+O --debug"'
          - os: ubuntu
            ruby: head
            experimental: true
    
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true
    
    - name: Run tests
      timeout-minutes: 5
      run: ${{matrix.env}} bundle exec rspec
